### ISSUE TITLE
Sass loader

### ISSUE THREAD

**Issue by shectermen** [RasCarlito/sails-hook-next#6]
next.config.js in root dir not working, and I do not understand how to use config/next.js conf:{}, please help, i want to get sass loader

**Comment by ghost** [comment]
Hi @shectermen !

Sorry for the delay. I just became a father so not much time to browse github 😅 

To make sass working with Next.js you need to use the next-plugins: https://github.com/zeit/next-plugins/tree/master/packages/next-sass

Just follow the instructions there and you should be fine!

Cheers

**Comment by shectermen** [comment]
can you show me example config/next.js  for next-sass ? I understood how to add 1 module, but a few did not work, you can specify the config in the standard version of nextjs , in advance, thanks

**Comment by shectermen** [comment]
And accept my congratulations !!

**Comment by shectermen** [comment]
it is not closed... problem not solved

**Comment by ghost** [comment]
Thanks @shectermen 😄 

The `config/next.js` is used to configure how the Next.js server will be integrated with Sails and not to configure which plugins will be integrated with Next.js.

Sorry I should update the readme to make it more clear and give examples.

Configuring SASS for Next.js is no different than without this Sails hook.

Install the extra dependencies

```
npm install --save @zeit/next-sass node-sass
```

Create a `next.config.js` file at the root of the project

```js
// next.config.js
const withSass = require('@zeit/next-sass')
module.exports = withSass()
```

Create a `pages/_document.js` file with a `<link />` pointing to `/_next/static/style.css`. That is where Next.js will compile SASS files to.

```jsx
// ./pages/_document.js
import Document, { Head, Main, NextScript } from 'next/document'

export default class MyDocument extends Document {
  render() {
    return (
      <html>
        <Head>
          <link rel="stylesheet" href="/_next/static/style.css" />
        </Head>
        <body>
          <Main />
          <NextScript />
        </body>
      </html>
    )
  }
}
```

Create a SASS file, e.g. `pages/index.scss`

```sass
$font-color: red;
h1 {
  color: $font-color;
}
```

Import the SASS file in your page

```jsx
import './index.scss'

export default () => <h1>This should be red!</h1>
```

I could maybe post an example repository but really this is not an issue with `sails-hook-next`. That is why I closed the issue.
I haven't tried to combine more plugins so I can't help you there.

Tell me if you're out of luck.

Cheers

**Comment by shectermen** [comment]
i try it, its not work, tomorrow i create the repo with this bug

**Comment by ghost** [comment]
@shectermen Any news? Did you get the opportunity to create a repo with the bug?

**Comment by shectermen** [comment]
sorry , now I also became a father, https://github.com/shectermen/sails-next

**Comment by ghost** [comment]
@shectermen Congrats to you too!! 😄

**Comment by shectermen** [comment]
thank you =)

**Comment by ghost** [comment]
I'm checking your repo out. Trying to make it work, I'll keep you posted ^^

**Comment by shectermen** [comment]
thank you very mutch

**Comment by shectermen** [comment]
thank you very mutch, can you explane me why it is worked? =) it's strange, I tried it, it did not work for me

**Comment by ghost** [comment]
Hey! Ok so you were completely right, the `next.config.js` file is not picked up when running a custom server for Next.js. Thanks for bearing with me until I accepted something was actually wrong 😅 

I created a PR on your project to show a working example https://github.com/shectermen/sails-next/pull/1

I couldn't get `next-compose-plugins` to work at all. But using the standard plugin composition technique it worked fine with `next-sass` and `next-images`.

I created a `/test` page to demonstrate it.

I will created another issue in this repository to better explain how this should be achieved when using Next.js with Sails 😃

**Comment by shectermen** [comment]
thank you, tell me if i can help

**Comment by ghost** [comment]
> thank you very mutch, can you explane me why it is worked? =) it's strange, I tried it, it did not work for me

Sure thing!

In your `config/next.js` file you didn't pass the configuration object to the `conf` key.

It should have been like this:

```js
const withPlugins = require('next-compose-plugins')
const withSass = require('@zeit/next-sass')

const config = withPlugins([
  [withSass]
])

module.exports.next = {
  server: {
    conf: config // Need to pass the resulting config object to Next.js
  }
}
```

_Small note: You don't have to include every key in the `module.exports.next` object if you don't want to override the defaults_

So this was my first try which should have worked but I could not get the `withPlugins` thing to work even though the code was exactly the same as in the examples in the docs but that is another issue I guess.

So in the end I just tried without `withPlugins`:

```js
const withSass = require('@zeit/next-sass')
const withImages = require('next-images')

module.exports.next = {
  server: {
    conf: withSass(withImages())
  }
}
```

**Comment by shectermen** [comment]
a little later I will try to make a repo with an example of a simple site with plug-ins, thank you

**Comment by ghost** [comment]
Awesome 👍 If you do you can post it back here as well or make a PR to this project modifying the readme to add "External ressources & examples" to the doc 😃 

I will close this issue.

Thanks again for sharing!

**Comment by markschellhas** [comment]
> 
> It should have been like this:
> 
> ```js
> const withPlugins = require('next-compose-plugins')
> const withSass = require('@zeit/next-sass')
> 
> const config = withPlugins([
>   [withSass]
> ])
> 
> module.exports.next = {
>   server: {
>     conf: config // Need to pass the resulting config object to Next.js
>   }
> }
> ```

I had the same issue, but with CSS. Thank you for maintaining this so well, this was a great help. And congrats to you both on becoming fathers!
